// MoodFlow Mood Catalogue — maps each mood to audio style, colors, and metadata
// Based on the MoodFlow Concept Document v1.0

export const MOODS = [
  {
    id: 'sad',
    emoji: '😔',
    label: 'Sad',
    subtitle: 'Melancholic',
    genre: 'Slow Blues · Ambient Soul',
    description: 'Slow tempo, minor keys, sparse piano or guitar. Validates the feeling without amplifying it.',
    colors: ['#1a1a2e', '#16213e', '#0f3460'],
    accentColor: '#5c6bc0',
    bpmRange: [55, 70],
    iconName: 'water-outline',
  },
  {
    id: 'happy',
    emoji: '😊',
    label: 'Happy',
    subtitle: 'Content',
    genre: 'Acoustic Lo-Fi · Bright Ambient',
    description: 'Warm chord progressions, gentle plucking, soft percussion. Feels like a sunny afternoon.',
    colors: ['#ff9a56', '#ff6f61', '#ffb347'],
    accentColor: '#ffb347',
    bpmRange: [85, 110],
    iconName: 'sunny-outline',
  },
  {
    id: 'energetic',
    emoji: '⚡',
    label: 'Energetic',
    subtitle: 'Pumped',
    genre: 'Upbeat Lo-Fi · Funk Instrumental',
    description: 'Mid-to-fast tempo, prominent bassline, syncopated drums. Drives momentum.',
    colors: ['#f7971e', '#ffd200', '#ff6b35'],
    accentColor: '#ffd200',
    bpmRange: [110, 130],
    iconName: 'flash-outline',
  },
  {
    id: 'ecstatic',
    emoji: '🌟',
    label: 'Ecstatic',
    subtitle: 'Joyful',
    genre: 'Euphoric Ambient · Cinematic Lift',
    description: 'Rising progressions, layered pads, light glassy textures. Feels expansive.',
    colors: ['#fc5c7d', '#6a82fb', '#fc5c7d'],
    accentColor: '#ff79b0',
    bpmRange: [100, 125],
    iconName: 'star-outline',
  },
  {
    id: 'hyped',
    emoji: '🔥',
    label: 'Hyped',
    subtitle: 'EDM Mode',
    genre: 'Deep House · Downtempo Electronic',
    description: '4/4 beat, synthesized pads, driving but not abrasive. Enough pulse to feel the energy.',
    colors: ['#eb3349', '#f45c43', '#ff6a00'],
    accentColor: '#ff4444',
    bpmRange: [130, 145],
    iconName: 'flame-outline',
  },
  {
    id: 'motivated',
    emoji: '💡',
    label: 'Motivated',
    subtitle: 'Rising',
    genre: 'Motivational Ambient · Cinematic Build',
    description: 'Gradual crescendos, orchestral or hybrid electronic. Built for tasks that need a push.',
    colors: ['#11998e', '#38ef7d', '#11998e'],
    accentColor: '#38ef7d',
    bpmRange: [90, 115],
    iconName: 'bulb-outline',
  },
  {
    id: 'focus',
    emoji: '💻',
    label: 'Deep Focus',
    subtitle: 'Coding',
    genre: 'Lo-Fi Hip-Hop · Binaural Ambient',
    description: 'Steady 70–90 BPM, subtle vinyl texture, no melodic hooks. Reduces cognitive load.',
    colors: ['#0f0c29', '#302b63', '#24243e'],
    accentColor: '#7c4dff',
    bpmRange: [70, 90],
    iconName: 'code-slash-outline',
  },
  {
    id: 'study',
    emoji: '📖',
    label: 'Study',
    subtitle: 'Reading',
    genre: 'Classical Minimal · Piano Ambient',
    description: 'Slow harmonic movement, sparse arrangement, predictable structure.',
    colors: ['#2c3e50', '#3498db', '#2980b9'],
    accentColor: '#64b5f6',
    bpmRange: [60, 80],
    iconName: 'book-outline',
  },
  {
    id: 'calm',
    emoji: '🧘',
    label: 'Calm',
    subtitle: 'Winding Down',
    genre: 'Ambient · Nature-Infused Electronic',
    description: 'Long sustain notes, gentle reverb, nature textures. Designed for decompression.',
    colors: ['#43cea2', '#185a9d', '#43cea2'],
    accentColor: '#80cbc4',
    bpmRange: [45, 65],
    iconName: 'leaf-outline',
  },
  {
    id: 'latenight',
    emoji: '🌙',
    label: 'Late Night',
    subtitle: 'Mellow',
    genre: 'Dark Lo-Fi · Night Ambient',
    description: 'Lower register, slower tempo, nocturnal textures. For late work sessions.',
    colors: ['#0d0d2b', '#1a1a3e', '#2d1b69'],
    accentColor: '#b388ff',
    bpmRange: [55, 75],
    iconName: 'moon-outline',
  },
];

export const getMoodById = (id) => MOODS.find((m) => m.id === id);

export const INTENSITY_LABELS = ['Gentle', 'Low', 'Medium', 'High', 'Intense'];
